"""Audit service (SVC-006): append-only atlas_event records.

Design invariants:
- Events are append-only; no deletes or updates.
- Each event gets a unique ID generated by the caller or auto-generated.
- All events are written atomically via the JSONL repository layer.
- Query support: filter by project_id, event_type, actor_id, date range.
- CCDash wiring: AuditService.emit forwards to CCDashClient when configured.
  Failures in CCDash export are logged but never propagate — audit is primary.
"""

from __future__ import annotations

import logging
import uuid
from datetime import datetime, timezone
from pathlib import Path
from typing import TYPE_CHECKING, Any

from app.models.audit import AuditEvent
from app.models.vocabulary import ActorType, AuditEventType
from app.repositories import jsonl as _jl

if TYPE_CHECKING:
    from app.services.ccdash_client import CCDashClient

logger = logging.getLogger(__name__)

_EVENTS_FILE = "events.jsonl"


class AuditRepository:
    """Append-only repository for AuditEvent records."""

    def __init__(self, registry_dir: Path) -> None:
        self._path = registry_dir / _EVENTS_FILE

    def append(self, event: AuditEvent) -> AuditEvent:
        """Append an audit event. Returns the persisted event."""
        record = event.model_dump(mode="json")
        _jl.append_record(self._path, record)
        return event

    def list(
        self,
        *,
        project_id: str | None = None,
        event_type: str | None = None,
        actor_id: str | None = None,
        since: datetime | None = None,
        limit: int | None = None,
    ) -> list[AuditEvent]:
        """Return audit events, newest-first, with optional filters.

        Args:
            project_id: Filter to events for a specific project.
            event_type: Filter to a specific AuditEventType value.
            actor_id: Filter to events by a specific actor.
            since: Include only events at or after this datetime.
            limit: Maximum number of events to return (applied after filtering).

        Returns:
            List of AuditEvent records, newest first.
        """
        records = _jl.read_all(self._path, include_deleted=False)

        if project_id is not None:
            records = [r for r in records if r.get("project_id") == project_id]
        if event_type is not None:
            records = [r for r in records if r.get("event_type") == event_type]
        if actor_id is not None:
            records = [r for r in records if r.get("actor_id") == actor_id]
        if since is not None:
            since_iso = since.isoformat()
            records = [r for r in records if r.get("timestamp", "") >= since_iso]

        # Newest first
        records = sorted(records, key=lambda r: r.get("timestamp", ""), reverse=True)

        if limit is not None:
            records = records[:limit]

        return [AuditEvent.model_validate(r) for r in records]


def _make_event(
    event_type: AuditEventType,
    target_type: str,
    target_id: str,
    *,
    actor_type: ActorType = ActorType.system,
    actor_id: str = "system",
    project_id: str | None = None,
    workspace_id: str | None = None,
    payload: dict[str, Any] | None = None,
    event_id: str | None = None,
) -> AuditEvent:
    """Construct an AuditEvent with a UTC timestamp and unique ID."""
    return AuditEvent(
        id=event_id or f"evt_{uuid.uuid4().hex[:16]}",
        timestamp=datetime.now(tz=timezone.utc),
        workspace_id=workspace_id,
        project_id=project_id,
        actor_type=actor_type,
        actor_id=actor_id,
        event_type=event_type,
        target_type=target_type,
        target_id=target_id,
        payload=payload,
    )


class AuditService:
    """Business logic for audit event emission and querying.

    Wraps AuditRepository with convenience emit helpers used by other services.

    CCDash wiring:
        Pass a CCDashClient instance via ``ccdash_client`` to automatically
        forward audit events to ccdash-events.jsonl.  Forwarding failures are
        caught and logged so they never interrupt the primary audit write.
    """

    def __init__(
        self,
        registry_dir: Path,
        *,
        ccdash_client: "CCDashClient | None" = None,
    ) -> None:
        self._repo = AuditRepository(registry_dir)
        self._ccdash = ccdash_client

    # ------------------------------------------------------------------
    # Emit helpers
    # ------------------------------------------------------------------

    def emit(
        self,
        event_type: AuditEventType,
        target_type: str,
        target_id: str,
        *,
        actor_type: ActorType = ActorType.system,
        actor_id: str = "system",
        project_id: str | None = None,
        workspace_id: str | None = None,
        payload: dict[str, Any] | None = None,
    ) -> AuditEvent:
        """Emit an arbitrary audit event and persist it.

        After persisting to the audit log, attempts to forward the event to
        CCDash (if a CCDashClient was provided at construction time).  CCDash
        export failures are caught and logged — they never interrupt audit.
        """
        event = _make_event(
            event_type,
            target_type,
            target_id,
            actor_type=actor_type,
            actor_id=actor_id,
            project_id=project_id,
            workspace_id=workspace_id,
            payload=payload,
        )
        persisted = self._repo.append(event)

        # Forward to CCDash — guard so audit is never blocked by export errors
        if self._ccdash is not None:
            try:
                self._ccdash.append_from_audit_event(persisted)
            except Exception as exc:  # noqa: BLE001
                logger.warning(
                    "CCDash export failed for event %s (%s): %s",
                    persisted.id,
                    event_type.value,
                    exc,
                )

        return persisted

    def emit_asset_added(
        self,
        asset_id: str,
        *,
        project_id: str | None = None,
        actor_id: str = "system",
        payload: dict[str, Any] | None = None,
    ) -> AuditEvent:
        """Emit asset_added event."""
        return self.emit(
            AuditEventType.asset_added,
            "asset",
            asset_id,
            actor_id=actor_id,
            project_id=project_id,
            payload=payload,
        )

    def emit_asset_promoted(
        self,
        asset_id: str,
        *,
        project_id: str | None = None,
        actor_id: str = "system",
        payload: dict[str, Any] | None = None,
    ) -> AuditEvent:
        """Emit asset_promoted event."""
        return self.emit(
            AuditEventType.asset_promoted,
            "asset",
            asset_id,
            actor_id=actor_id,
            project_id=project_id,
            payload=payload,
        )

    def emit_policy_denied(
        self,
        target_id: str,
        target_type: str,
        *,
        actor_id: str = "system",
        project_id: str | None = None,
        payload: dict[str, Any] | None = None,
    ) -> AuditEvent:
        """Emit policy_denied event."""
        return self.emit(
            AuditEventType.policy_denied,
            target_type,
            target_id,
            actor_id=actor_id,
            project_id=project_id,
            payload=payload,
        )

    def emit_asset_linked(
        self,
        asset_id: str,
        *,
        project_id: str | None = None,
        actor_id: str = "system",
        payload: dict[str, Any] | None = None,
    ) -> AuditEvent:
        """Emit asset_linked event."""
        return self.emit(
            AuditEventType.asset_linked,
            "asset",
            asset_id,
            actor_id=actor_id,
            project_id=project_id,
            payload=payload,
        )

    def emit_asset_archived(
        self,
        asset_id: str,
        *,
        project_id: str | None = None,
        actor_id: str = "system",
        payload: dict[str, Any] | None = None,
    ) -> AuditEvent:
        """Emit asset_archived event."""
        return self.emit(
            AuditEventType.asset_archived,
            "asset",
            asset_id,
            actor_id=actor_id,
            project_id=project_id,
            payload=payload,
        )

    def emit_deleted(
        self,
        target_id: str,
        target_type: str,
        *,
        project_id: str | None = None,
        actor_id: str = "system",
        payload: dict[str, Any] | None = None,
    ) -> AuditEvent:
        """Emit generic deleted event."""
        return self.emit(
            AuditEventType.deleted,
            target_type,
            target_id,
            actor_id=actor_id,
            project_id=project_id,
            payload=payload,
        )

    # ------------------------------------------------------------------
    # Query
    # ------------------------------------------------------------------

    def list_events(
        self,
        *,
        project_id: str | None = None,
        event_type: str | None = None,
        actor_id: str | None = None,
        since: datetime | None = None,
        limit: int | None = None,
    ) -> list[AuditEvent]:
        """Query audit events with optional filters."""
        return self._repo.list(
            project_id=project_id,
            event_type=event_type,
            actor_id=actor_id,
            since=since,
            limit=limit,
        )
